[package]
name = "kf_compile_tool"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
kfct_lib = { path = "..//kfct_lib" }
gumdrop = "0.8.*"
