# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "kfct_lib"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
zip = { version = "2.*", features = [
    "deflate-flate2",
], default-features = false }
flate2 = { version = "1.*", features = ["zlib-rs"], default-features = false }
zip-extensions = "0.8.*"
configparser = "3.*"
walkdir = "2.*"
